services:
  taf-be:
    image: overzoom/taf-be:latest
    container_name: taf-be
    mem_limit: 512m
    mem_reservation: 256m
    ports:
      - "7480:8080"
    env_file:
      - .env
    depends_on:
      - tafdb
    networks:
      - taf_net
    restart: always

  tafdb:
    image: mongo
    container_name: tafdb
    mem_limit: 512m
    mem_reservation: 256m
    logging:
      options:
        max-size: 200m
    ports:
      - "7481:27017"
    volumes:
      - tafdb:/data/db
    env_file:
      - .env
    networks:
      - taf_net
    restart: always

networks:
  taf_net:
    driver: bridge

volumes:
  tafdb:
