server:
    port: 8080

spring:
    application:
        name: taf
    data:
        mongodb:
            authentication-database: admin
            database: ${SPRING_DATA_MONGODB_DATABASE:tafdb}
            host: ${SPRING_DATA_MONGODB_HOST:localhost}
            password: ${SPRING_DATA_MONGODB_PASSWORD:secr3t}
            port: ${SPRING_DATA_MONGODB_PORT:7481}
            username: ${SPRING_DATA_MONGODB_USERNAME:admin}
            auto-index-creation: true
    servlet:
        multipart:
            max-file-size: 2MB
            max-request-size: 2MB  
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: ${COGNITO_CLIENT_ID}
                        client-secret: ${COGNITO_CLIENT_SECRET}
                        scope:
                        - email
                        - openid
                        - profile
                        redirect-uri: http://localhost:4200/login/oauth2/code/cognito
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_ezfmvZVI2
                        user-name-attribute: username
            resourceserver:
                jwt:
                    issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_bSXSXHEow            

logging:
  level:
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.client: DEBUG
    org.springframework.security.oauth2.jwt: DEBUG
    org.springframework.security.oauth2.server.resource: DEBUG
    org.springframework.security.oauth2.server.resource.authentication: DEBUG
    org.springframework.security.oauth2.server.resource.web: DEBUG
    org.springframework.security.oauth2.server.resource.introspection: DEBUG
    org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationConverter: DEBUG
    org.springframework.security: DEBUG

cognito:
  region: eu-central-1                        