server:
    port: 8080

spring:
    application:
        name: taf
    data:
        mongodb:
            authentication-database: admin
            database: ${SPRING_DATA_MONGODB_DATABASE:tafdb}
            host: ${SPRING_DATA_MONGODB_HOST:localhost}
            password: ${SPRING_DATA_MONGODB_PASSWORD:secr3t}
            port: ${SPRING_DATA_MONGODB_PORT:7481}
            username: ${SPRING_DATA_MONGODB_USERNAME:admin}
            auto-index-creation: true
    servlet:
        multipart:
            enabled: true
            max-file-size: 2MB
            max-request-size: 2MB  
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: ${COGNITO_CLIENT_ID}
                        client-secret: ${COGNITO_CLIENT_SECRET}
                        scope:
                        - email
                        - openid
                        - profile
                        redirect-uri: http://localhost:4200/login/oauth2/code/cognito
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_ezfmvZVI2
                        user-name-attribute: username
            resourceserver:
                jwt:
                    issuer-uri: https://cognito-idp.eu-central-1.amazonaws.com/eu-central-1_bSXSXHEow            

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
    org.springframework.data.mongodb.core.MongoDatabaseFactory: DEBUG
    org.springframework.data.mongodb.core.MongoCollectionUtils: DEBUG
    org.springframework.data.mongodb.core.mapping.MongoMappingContext: DEBUG

cognito:
  region: eu-central-1        
  user-pool-id: eu-central-1_ezfmvZVI2
  user-pool-client-id: ${COGNITO_CLIENT_ID}
  user-pool-client-secret: ${COGNITO_CLIENT_SECRET}     

springdoc:
    api-docs:
        path: /api-docs
    swagger-ui:
        path: /swagger-ui.html  
        operationsSorter: method        

openapi:
    service:
        title: TAF+ API v3 Doc
        version: 1.0.0
        url: ${OPENAPI_URL:http://localhost:8080/v3/api-docs}             