name: Build & Deploy Spring-Boot Container

on:
  push:
    branches:
      - master
      - develop

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/taf-be:${{ github.ref == 'refs/heads/develop' && 'staging' || 'latest' }}
          build-args: |
            SPRING_PROFILES_ACTIVE=${{ github.ref == 'refs/heads/develop' && 'staging' || 'production' }}

  deploy:
    name: SSH deploy to server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for consistency)
        uses: actions/checkout@v4

      - name: Deploy on Server TAF-BE
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/manager/orchestrator/taf
            # Determina se siamo su staging o produzione
            if [ "${GITHUB_REF}" == "refs/heads/develop" ]; then
              IMAGE_TAG="staging"
              SERVICE="taf-be-staging"
              PROFILE="staging"
            else
              IMAGE_TAG="latest"
              SERVICE="taf-be"
              PROFILE="production"
            fi

            # Passa il profilo come variabile d'ambiente per Docker
            export SPRING_PROFILES_ACTIVE=$PROFILE

            # Assicurati che l'immagine sia aggiornata
            docker compose pull $SERVICE

            # Ricrea solo il servizio taf-be in background
            docker compose up -d $SERVICE
