name: Build & Deploy Staging Spring-Boot Container

on:
  push:
    branches:
      - develop

jobs:
  build-and-push:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/taf-be:staging

  deploy:
    name: SSH deploy to staging server
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository (for consistency)
        uses: actions/checkout@v4

      # ===== Deploy on Staging Server =====
      - name: Deploy on Staging Server TAF-BE
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_SSH_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /home/manager/orchestrator/taf

            # Update Docker image
            docker compose pull taf-be-staging

            # Recreate only the staging service
            docker compose up -d taf-be-staging
